title: Everything
description: A adaptation of Fig. 2 "Plot of All Objects" in Lineweaver, C. H. and Patel, V. M., “All objects and some questions”, American Journal of Physics, vol. 91, no. 10, AIP, pp. 819–825, 2023. doi:10.1119/5.0150209. 
